# =====================================================
# Docker Compose: Laravel + Nginx + PHP + MariaDB + phpMyAdmin
# version: '3.8'  # 明示推奨
# =====================================================

services:
  # ===============================
  # Nginx: Webサーバー
  # ===============================
  nginx:
    build:
      context: ./docker-config/nginx
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    ports:
      - "${NGINX_PORT}:80"  # ホスト:コンテナ のポートマッピング
    volumes:
      - ./src:/var/www/src                   # Laravelアプリのマウント
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-config/logs:/var/log/nginx
    depends_on:
      - php                              # PHP(FPM)が起動してからNginxが起動
    networks:
      - app-network

  # ===============================
  # PHP-FPM: Laravel 実行環境
  # ===============================
  php:
    build:
      context: ./docker-config/php
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-php
    working_dir: /var/www/src
    volumes:
      - ./src:/var/www/src
      - ./docker-config/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker-config/logs:/var/log/php-fpm
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${MARIADB_DATABASE}
      DB_USERNAME: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      TZ: ${TZ}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # ===============================
  # MariaDB: データベース
  # ===============================
  db:
    image: mariadb:${MARIADB_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      TZ: ${TZ}
    volumes:
      - db-data:/var/lib/mysql                                  # DB永続化
      - ./docker-config/db/conf/my.conf:/etc/mysql/conf.d/my.conf # DB設定ファイル
      - ./docker-config/db/sql:/docker-entrypoint-initdb.d      # 初期SQL自動実行
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  # ===============================
  # phpMyAdmin: データベースGUI管理
  # ===============================
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    platform: linux/amd64
    container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: ${MARIADB_USER}
      PMA_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
